/**
 * Local-development defaults.
 *
 * The deployed copy of this file is regenerated by build/build.mjs from the
 * PL_API_BASE repository variable and frontend/CNAME — edits here only affect
 * running the console from a local checkout.
 */
window.PL_ADMIN_CONFIG = {
  apiBase: 'http://localhost:8080',
  siteUrl: 'http://localhost:4173',
};
